SUPABASE_URL = "https://xfrbberofbcdsflkzcnz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcmJiZXJvZmJjZHNmbGt6Y256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMDg5ODYsImV4cCI6MjA5Mzg4NDk4Nn0.utfnDbNf4Q20kKJ5LIM8cpdlZx0I30H4LKl-3ZuwP_g"

